quotes = {
  "William Shakespeare" => "What's in a name? That which we call a rose by any other name would smell as sweet.",
  "Barbara Streisand" => "I love things that are indescribable, like the taste of an avocado or the smell of a gardenia.",
  "Yotam Ottolenghi" => "I love my garlic press; in fact, it is probably my one true desert island gadget. But I'm happy to put it aside whenever the smell and sweet taste of slow-cooked garlic is called for.",
  "Vladimir Nabokov" => "Nothing revives the past so completely as a smell that was once associated with it.",
  "Leonardo Davinci" => "There are four Powers: memory and intellect, desire and covetousness. The two first are mental and the others sensual. The three senses: sight, hearing and smell cannot well be prevented; touch and taste not at all.",
  "Jennifer Lopez" => "I judge people on how they smell, not how they look.",
  "Cameron Mackintoch" => "An old building is like a show. You smell the soul of a building. And the building tells you how to redo it.",
  "Rihanna" => "I love reading people. I really enjoy watching, observing, and being able to figure out a person, the reason they wore that dress, the reason they smell the way they do.",
  "Friedrich Nietschze" => "Does wisdom perhaps appear on the earth as a raven which is inspired by the smell of carrion?",
  "Sylvia Plath" => "Now and then, when I grow nostalgic about my ocean childhood - the wauling of gulls and the smell of salt, somebody solicitous will bundle me into a car and drive me to the nearest briny horizon.",
  "Haruki Murakami" => "When I write about a 15-year old, I jump, I return to the days when I was that age. It's like a time machine. I can remember everything. I can feel the wind. I can smell the air. Very actually. Very vividly.",
  "Trixie Mattel" => "As a kid, I wasn't allowed to have girl toys, but I would take my cousin's My Little Pony and smell it. That weird, synthetic, fruity-sweet smell - that's how I wanted to look. I wanted to look like this fabricated toy. I wanted to look like you could pull a string on my back, and I would say, like, six catchphrases.",
  "Joan Rivers" => "My eyes opened, and the first thing I thought of when I could put thoughts together was I want to be in show business. Never wanted anything else. I used to sneak in the costume room at my nursery school and smell the costumes.",
  "David Lynch" => "I like watercolours. I like acrylic paint... a little bit. I like house paint. I like oil-based paint, and I love oil paint. I love the smell of turpentine and I like that world of oil paint very, very, very much.",
  "Sophie Dahl" => "When I write about things, it's a lot to do with sense memory. How things smell and taste can bring incredible memories flooding back and transport you in an instant to another time and place.",
}
